services:
  pgvector:
    hostname: pgvector-db
    image: ankane/pgvector
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=vectorpg
      - POSTGRES_PASSWORD=vectorpg
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - pgvector-network
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  pgvector-network:
    driver: bridge
    external: true
