services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: media_crawler
      MYSQL_USER: terry
      MYSQL_PASSWORD: 123123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: